debug: false
spring:
  cloud:
    gcp:
      credentials:
        location: file:/home/codegeek/Downloads/cmoportal-c3232d99d73c.json
      project-id: cmoportal
  jpa:
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:cmoportal
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host:
    port:
    username:
    password:



